/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EnrollmentView = IDL.Record({
  'completedLessons' : IDL.Vec(IDL.Nat),
  'courseId' : IDL.Nat,
});
export const UserProfileView = IDL.Record({
  'assessments' : IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'skillRatings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'subjectScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  }),
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'grade' : IDL.Text,
});
export const CareerPath = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const CertificateView = IDL.Record({
  'issueDate' : Time,
  'studentName' : IDL.Text,
  'courseName' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'relatedCareer' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCareerPath' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addLessonToCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeLesson' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
  'getCallerEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentView)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getCertificates' : IDL.Func([], [IDL.Vec(CertificateView)], ['query']),
  'getCourseDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getEnrollment' : IDL.Func([IDL.Nat], [IDL.Opt(EnrollmentView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      ],
      [],
      [],
    ),
  'saveStudentProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateAssessments' : IDL.Func(
      [
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EnrollmentView = IDL.Record({
    'completedLessons' : IDL.Vec(IDL.Nat),
    'courseId' : IDL.Nat,
  });
  const UserProfileView = IDL.Record({
    'assessments' : IDL.Record({
      'interests' : IDL.Vec(IDL.Text),
      'skillRatings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      'subjectScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    }),
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'grade' : IDL.Text,
  });
  const CareerPath = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const CertificateView = IDL.Record({
    'issueDate' : Time,
    'studentName' : IDL.Text,
    'courseName' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'relatedCareer' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCareerPath' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addLessonToCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeLesson' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
    'getCallerEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentView)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getCertificates' : IDL.Func([], [IDL.Vec(CertificateView)], ['query']),
    'getCourseDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getEnrollment' : IDL.Func([IDL.Nat], [IDL.Opt(EnrollmentView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        ],
        [],
        [],
      ),
    'saveStudentProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateAssessments' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };