/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath {
  'title' : string,
  'description' : string,
  'requiredSkills' : Array<string>,
}
export interface CertificateView {
  'issueDate' : Time,
  'studentName' : string,
  'courseName' : string,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'relatedCareer' : string,
}
export interface EnrollmentView {
  'completedLessons' : Array<bigint>,
  'courseId' : bigint,
}
export interface Lesson { 'id' : bigint, 'title' : string, 'content' : string }
export type Time = bigint;
export interface UserProfileView {
  'assessments' : {
    'interests' : Array<string>,
    'skillRatings' : Array<[string, bigint]>,
    'subjectScores' : Array<[string, bigint]>,
  },
  'interests' : Array<string>,
  'name' : string,
  'grade' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCareerPath' : ActorMethod<[string, string, Array<string>], undefined>,
  'addCourse' : ActorMethod<[string, string, string], bigint>,
  'addLessonToCourse' : ActorMethod<[bigint, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeLesson' : ActorMethod<[bigint, bigint], undefined>,
  'enrollInCourse' : ActorMethod<[bigint], undefined>,
  'getCallerEnrollments' : ActorMethod<[], Array<EnrollmentView>>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerPaths' : ActorMethod<[], Array<CareerPath>>,
  'getCertificates' : ActorMethod<[], Array<CertificateView>>,
  'getCourseDetails' : ActorMethod<[bigint], [] | [Course]>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getEnrollment' : ActorMethod<[bigint], [] | [EnrollmentView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      Array<[string, bigint]>,
      Array<[string, bigint]>,
    ],
    undefined
  >,
  'saveStudentProfile' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'updateAssessments' : ActorMethod<
    [Array<string>, Array<[string, bigint]>, Array<[string, bigint]>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];